Module5:Blog app - Views
derrick1451/Blog-app pull request #6
Opened 2023-09-07 19:41 UTC by derrick1451

### Blog app - Views
### Requirements
- Implement the design from the sneak peek wireframes.
  - Styling is nice to have but focus on making sure everything functions first. (Note: Ignore login logic, you would be using Devise in coming milestone)
  - Use methods that you have created in the [Blog App - processing data in models](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project.md).
  - Hint: In order to see some posts or comments, you might need to add some data to your database as described [here](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project.md#use-models-to-insert-data).
  - Make sure that there are [no linter errors](https://github.com/microverseinc/linters-config).
  - Make sure that you have used correct [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md).
- Make sure that you documented your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).
### Highlights
- RESOLVED

2023-09-07 22:26 UTC, Munsa1 requested changes
Hi @derrick1451, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Implemented Views :heavy_check_mark: 
Correct Git Flow :heavy_check_mark: 
Descriptive Pr :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

### Take Note :warning: 
- [ ] The biggest requirement is the design of your views, kindly follow the given wireframe design for a basic UI as what we have now is no design at all
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-07 22:26 UTC, Munsa1 commented on app/views/users/index.html.erb
> +<%end%>
- [ ] The users index page should match the given wireframe design, all components in the given wireframe should be added to your design. Kindly implement this.

Your design
![image](https://github.com/derrick1451/Blog-app/assets/81932478/1680c7d7-adbe-4df4-8f1d-d5897efeeaab)


Given wireframe
![image](https://github.com/derrick1451/Blog-app/assets/81932478/89933fef-902c-4509-94a4-df3c8bcaa555)

- [ ] Clicking on each user should take you to their show page, Kindly implement this. Currently nothing happens

2023-09-07 22:26 UTC, Munsa1 commented on app/views/users/show.html.erb
> +<%end%>
- [ ] The users show page should follow the given wireframe for design as well. Kindly add the see all posts button to your design and all other missing components.

Your design
![image](https://github.com/derrick1451/Blog-app/assets/81932478/4c893d55-76a9-4574-94fd-b7319d24ba06)


Given design
![image](https://github.com/derrick1451/Blog-app/assets/81932478/b3585791-2f55-446d-bdf5-6c7851a08742)


#### Note that all elements in the given wireframes should be implemented

2023-09-07 22:26 UTC, Munsa1 commented on app/views/users/show.html.erb
> +<%end%>
- [ ] Once you have added it, clicking on the **See all Post** link should open the user's post index as displayed on the [wireframe](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_user_all_posts.png)

2023-09-07 22:26 UTC, Munsa1 commented on app/views/posts/index.html.erb
> +<li><%=comments.Text%></li>
- [ ] Kindly Use `five_most_recent_comments` method created in the Post model to render 5 most recent comments in the `app/views/posts/index.html.erb` page

2023-09-07 22:26 UTC, Munsa1 commented on app/views/posts/index.html.erb
> +<li>post :<%=post.id%> <br> Text :<%=post.Text%> <br> Coments :<%=post.CommentsCounter%> <br> Likes :<%=post.LikesCounter%>  </li>
- [ ] Kindly ensure your design matches the given design. Again here as for everywhere all components in the given design should be added to your design.

Your design
![image](https://github.com/derrick1451/Blog-app/assets/81932478/38639a40-d55f-4e43-af9b-08a8bff81f96)


Given design
![image](https://github.com/derrick1451/Blog-app/assets/81932478/eb469550-34f7-4700-aedf-a05d27c8574e)

2023-09-07 22:26 UTC, Munsa1 commented on app/views/posts/show.html.erb
> +  <%end%>
- [ ] The post show page should also follow the given design and should implement all the given elements on the page.

Your design
![image](https://github.com/derrick1451/Blog-app/assets/81932478/a0f4c069-ae9f-44d1-954a-ec2abff0bd0b)

Given frame
![image](https://github.com/derrick1451/Blog-app/assets/81932478/aee408ca-c525-49ee-bda6-966e92b28e4c)

2023-09-07 22:26 UTC, Munsa1 commented on app/views/posts/show.html.erb
> +  <%@post.five_most_recent_comments.each do |comment|%>
- [ ] The `five_most_recent_comments` method should not be used here on the show page, here we want to show the post with all the comments, we should use that method on the post index page. Kindly do so

2023-09-08 21:50 UTC, Munsa1 requested changes
Hi @derrick1451, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
Implemented Most Of The Requested Changes :heavy_check_mark: 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-08 21:57 UTC, Munsa1 commented
- [ ] Clicking on each user should take the user to the user index page, but currently, there is an error, kindly fix it.

User index
![image](https://github.com/derrick1451/Blog-app/assets/81932478/380653b6-23f5-424f-a07b-d484c45bbc14)

After clicking on each user
![image](https://github.com/derrick1451/Blog-app/assets/81932478/3ae9e787-5f2e-4b9e-8984-9997d0b17221)

![image](https://github.com/derrick1451/Blog-app/assets/81932478/0f0b9a72-e0c4-4da3-97f2-7847c78597ad)

## To the next reviewer
- [ ] Since I have no access to the user show page I am unable to determine if these two issues were resolved. 
- [issue 1](https://github.com/derrick1451/Blog-app/pull/6#discussion_r1319144230)
- [issue 2](https://github.com/derrick1451/Blog-app/pull/6#discussion_r1319145543)

2023-09-08 22:08 UTC, derrick1451 commented
@Munsa1 Yeah l saw that error as well but l guess you haven't pull my current work because when you check my pull request you could see that l actually made a new commit and l pushed it but l guess you had already started reviewing

2023-09-08 22:25 UTC, derrick1451 commented
dear reviewer this the video confirmation
- https://www.loom.com/share/755fff75770c46fe9b3e1dab4f4d259f?sid=b6a9f82d-d16b-424e-8cf3-3ace3e00010c

2023-09-08 22:31 UTC, Munsa1 commented
> @Munsa1 Yeah l saw that error as well but l guess you haven't pull my current work because when you check my pull request you could see that l actually made a new commit and l pushed it but l guess you had already started reviewing

@derrick1451 understood but please for the next projects DO not push on a PR once you have submitted it for review

2023-09-08 23:12 UTC, Alfredbis29 approved these changes
# STATUS: APPROVED   
 ## Hi  @derrick1451 
Your project is complete! There is nothing else to say other than... Great job clap Congratulations! :tada:
 
 TO HIGHLIGHT:
 
 * Your project is professional :white_check_mark:
 * Good Job :+1:
 
 Now you can merge this branch and move on 1st_place_medal: HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :

![](https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966)
 
 ## Optional suggestions

- [x] Keep doing the good work :+1: 

 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
 
Cheers and Happy coding! :clap:  :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @Alfredbis29 in your question so I can receive the notification.
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-09 12:20 UTC, merged